# Generated by Django 2.2.16 on 2023-04-19 18:47

import csv
import os

from django.db import migrations
from foodgram.settings import BASE_DIR

DATA_DIR = os.path.join(BASE_DIR, 'data')
DATA_PATH = os.path.join(DATA_DIR, 'ingredients.csv')




def add_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    with open(DATA_PATH, 'r', encoding='utf-8') as csv_file:
        reader = csv.reader(csv_file)
        header = next(reader)
        ingredients = []
        for row in reader:
            name = row[0]
            ingredient = next((b for b in ingredients if b.name==name), None)
            if not ingredient:
                ingredient = Ingredient(name=row[0], measurement_unit=row[1])
                ingredients.append(ingredient)
        Ingredient.objects.bulk_create(ingredients)

def remove_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    Ingredient.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_add_tags'),
    ]

    operations = [
        migrations.RunPython(
            add_ingredients,
            remove_ingredients
        )
    ]
