# Generated by Django 2.2.16 on 2023-04-25 06:16

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230425_0026'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='prevent_self_subscription'),
        ),
    ]
